version: '3.8'
services:
  app:
    build: 
       context: "."
    tty: true
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./app
        target: /home/docker/vall_e_x_api

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
